# Need vite proxy server
server {
    listen 80;
    server_name localhost;

    root /var/www/html/laravel/public;
    index index.php;

    # Laravel API + web routes
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handler
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # security
    location ~ /\. {
        deny all;
    }
}