# No need vite proxy

server {
    listen 80;
    server_name your-domain.com;

    # -------------------------
    # React frontend (STATIC)
    # -------------------------
    root /var/www/html/react/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # -------------------------
    # Laravel API
    # -------------------------
    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # -------------------------
    # PHP-FPM
    # -------------------------
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/html/laravel/public$fastcgi_script_name;
    }

    # block hidden files
    location ~ /\. {
        deny all;
    }
}